django/func_sample/diary/urls.py
from django.urls import path
from . import views

app_name = 'diary'

urlpatterns = [
    path('', views.index, name='index'), # /diary
    path('add/', views.add, name='add'), # /diary/add
    path('update/<int:pk>/', views.update, name='update'),  # /diary/update/整数
    path('delete/<int:pk>/', views.delete, name='delete'),  # /diary/delete/整数
    path('detal/<int:pk>/', views.detal, name='detal'),  # /diary/detal/整数
]

django/func_sample/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('diary/', include('diary.urls')),
]

django/func_sample/diary/models.py
from django.db import models

# django では, datetime.nowの変わりのtimezone.nowで現在の時間を示す
from django.utils import timezone


class Day(models.Model):
    title = models.CharField('タイトル', max_length=200)
    text = models.TextField('本文')
    date = models.DateTimeField('日付', default=timezone.now)

django/func_sample/diary/forms.py
from django import forms
from .models import Day


class DayCreateForm(forms.ModelForm):

    class Meta:
        model = Day
        fields = ('title', 'text', 'date')

django/func_sample/diary/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import DayCreateForm
from .models import Day
# from django.http import HttpResponse

def index(request):
    # aboutページ
    context = {
        'day_list':Day.objects.all(),
    }
    return render(request, 'diary/day_list.html',context)

def add(request):

    # 送信内容元にフォームを作成する。POSTじゃなければ秋のフォームで送る
    form = DayCreateForm(request.POST or None)

    # method=POST（送信ボタン押下時に入力内容が問題ない場合に実行）
    if request.method == 'POST' and form.is_valid():
        form.save()
        return redirect('diary:index')
    # 通常のページアクセス
    context = {
        'form':form
    }
    return render(request, 'diary/day_form.html', context)

def update(request,pk):

    # urlのPを基に、Dayを取得
    day = get_object_or_404(Day, pk=pk)

    # 送信内容元にフォームを作成する。POSTじゃなければ秋のフォームで送る
    form = DayCreateForm(request.POST or None, instance=day)

    # method=POST（送信ボタン押下時に入力内容が問題ない場合に実行）
    if request.method == 'POST' and form.is_valid():
        form.save()
        return redirect('diary:index')

    # 通常のページアクセス
    context = {
        'form':form
    }
    return render(request, 'diary/day_form.html', context)

def delete(request,pk):

    # urlのPを基に、Dayを取得
    day = get_object_or_404(Day, pk=pk)

    # method=POST（送信ボタン押下時に入力内容が問題ない場合に実行）
    if request.method == 'POST':
        day.delete()
        return redirect('diary:index')

    # 通常のページアクセス
    context = {
        'day':day,
    }
    return render(request, 'diary/day_config_delete.html', context)

def detal(request,pk):

    # urlのPを基に、Dayを取得
    day = get_object_or_404(Day, pk=pk)

    # 通常のページアクセス
    context = {
        'day':day,
    }
    return render(request, 'diary/day_detal.html', context)

django/func_sample/diary/templates/diary/base.html
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>
      {% block title %}{% endblock %}
    </title>

  </head>
  <body>
    <nav class="container">
        <nav class="nav">
          <a class="nav-link" href="{% url 'diary:index'%}">一覧</a>
          <a class="nav-link" href="{% url 'diary:add'%}">追加</a>
        </nav>
        {% block content %}
        {% endblock %}
    <nav class="container">

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

django/func_sample/diary/templates/diary/day_config_delete.html
{% extends 'diary/base.html' %}

{% block title %}Diary Page !{% endblock %}

{% block content %}
<h1>日記を記入して !</h1>
<form action="" method="POST">
    <table class = "table">
        <tr>
            <th>タイトル</th>
            <td>{{ day.title }}</td>
        </tr>
        <tr>
            <th>本文</th>
            <td>{{ day.text}}</td>
        </tr>
        <tr>
            <th>日付</th>
            <td>{{ day.date}}</td>
        </tr>
    </table>
    <p>こちらのデータを削除します。</p>
    <button type="submit" class="btn btn-primary">submit</button>
    {% csrf_token %}
</form>
{% endblock %}

django/func_sample/diary/templates/diary/day_detal.html
{% extends 'diary/base.html' %}

{% block title %}Diary Page !{% endblock %}

{% block content %}
<h1>日記を記入して !</h1>
    <table class = "table">
        <tr>
            <th>タイトル</th>
            <td>{{ day.title }}</td>
        </tr>
        <tr>
            <th>本文</th>
            <td>{{ day.text | linebreaksbr}}</td>
        </tr>
        <tr>
            <th>日付</th>
            <td>{{ day.date}}</td>
        </tr>
    </table>
{% endblock %}

django/func_sample/diary/templates/diary/day_form.html
{% extends 'diary/base.html' %}

{% block title %}Diary Page !{% endblock %}

{% block content %}
<h1>日記を記入して !</h1>
<form action="" method="POST">
    <table class = "table">
        <tr>
            <th>{{ form.title.label }}</th>
            <td>{{ form.title }}</td>
        </tr>
        <tr>
            <th>{{ form.text.label}}</th>
            <td>{{ form.text}}</td>
        </tr>
        <tr>
            <th>{{ form.date.label}}</th>
            <td>{{ form.date}}</td>
        </tr>
    </table>
    <button type="submit" class="btn btn-primary">submit</button>
    {% csrf_token %}
</form>
{% endblock %}

django/func_sample/diary/templates/diary/day_list.html
{% extends 'diary/base.html' %}

{% block title %}Diary Page !{% endblock %}

{% block content %}
<h1>日記一覧</h1>
<table class = "table">
    <thead>
        <tr>
            <th>タイトル</th>
            <th>日付</th>
            <th>#</th>
            <th>#</th>
        </tr>
    </thead>
    <tbody>
        {% for day in day_list %}
        <tr>
            <td><a href="{% url 'diary:detal' day.pk%}">{{day.title}}</a></td>
            <td>{{day.date}}</td>
            <td><a href="{% url 'diary:update' day.pk%}">更新</a></td>
            <td><a href="{% url 'diary:delete' day.pk%}">削除</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>>
{% endblock %}